World Saves
QuentinGruber/h1z1-server pull request #1030
Opened 2022-07-25 19:42 UTC by Z1Meme

2022-08-05 02:48 UTC, Z1Meme commented
@QuentinGruber Character saving works for both single and multiplayer (should not require a database reset), and vehicle saving is ready for when we have positionupdates fixed since we have some cleanup to do there and they don't work correctly rn.

2022-08-05 02:50 UTC, Z1Meme commented
Branch can be deleted btw

2022-08-05 09:27 UTC, QuentinGruber commented
I'm reviewing that today @Z1Meme 🤠

2022-08-05 10:26 UTC, QuentinGruber commented
Also this should be a feature easy to disable ( some servers don't want to store characters data and others )

2022-08-07 17:54 UTC, QuentinGruber commented
So i've spot 3 issues:

* Old characters can't be used
* Death from collision damage on spawn happens almost everytime
* I saw the log once and it only concern solo play but we shouldn't save circular structure to json ( didn't know which structure it was )

For the code and the way you structured it, it's well done 🤠

2022-08-07 17:56 UTC, QuentinGruber requested changes

2022-08-07 17:56 UTC, QuentinGruber commented on src/servers/ZoneServer2016/zonepackethandlers.ts
> +      //client.character.positionUpdate = packet.data;
if we remove it, we should remove the usage of it when sending LightweightToFullPc

2022-08-07 17:59 UTC, QuentinGruber commented
> So i've spot 3 issues:
> 
> * Old characters can't be used
> * Death from collision damage on spawn happens almost everytime
> * I saw the log once and it only concern solo play but we shouldn't save circular structure to json ( didn't know which structure it was )
> 
> For the code and the way you structured it, it's well done 🤠

Also 2015 version is broken with these changes, maybe we should create legacy functions for it

2022-08-09 23:15 UTC, Z1Meme commented
> > So i've spot 3 issues:
> > 
> > * Old characters can't be used
> > * Death from collision damage on spawn happens almost everytime
> > * I saw the log once and it only concern solo play but we shouldn't save circular structure to json ( didn't know which structure it was )
> > 
> > For the code and the way you structured it, it's well done 🤠
> 
> Also 2015 version is broken with these changes, maybe we should create legacy functions for it

- Old characters should just be deleted, they don't really matter anyways
- Death / damage from collision damage is fixed
- Can't reproduce that circular json issue
- Can't reproduce the 2015 issue, it works for me on both singleplayer and multiplayer, and as far as I know nothing was edited having to do with 2015

2022-08-09 23:16 UTC, Z1Meme commented
> Also this should be a feature easy to disable ( some servers don't want to store characters data and others )

Done
`process.env.ENABLE_SAVES`

2022-08-13 21:41 UTC, Z1Meme commented
@QuentinGruber this is ready to merge when you have some time

2022-08-14 08:05 UTC, QuentinGruber commented
I was thinking we could add some versioning to this. In the Worlds collection each world should have the version of the save system it generated, so that it wipes the world automatically if a newer version is used

2022-08-14 08:11 UTC, QuentinGruber approved these changes
🥳

2022-08-14 08:12 UTC, merged