Feature/Moderation tools
QuentinGruber/h1z1-server pull request #1076
Opened 2022-09-21 16:17 UTC by avcio9

2022-09-21 16:18 UTC, avcio9 commented
No need to store the spectator vehicle, with the spectator base you have to disconnect from server in order to get out of it

2022-09-30 16:33 UTC, QuentinGruber requested changes

2022-09-30 16:33 UTC, QuentinGruber commented on package.json
> +    "discord-webhook-node": "^1.1.8",
should be a fixed version since it's a third-party dependency "discord-webhook-node": "1.1.8" and rerun `npm i` to updt lockfile.

2022-10-04 12:27 UTC, QuentinGruber requested changes

2022-10-04 13:32 UTC, avcio9 commented on src/servers/ZoneServer2016/zoneserver.ts
> +      //if (vehicle.vehicleId == VehicleIds.SPECTATE) continue; //ignore spectator cam // shouldnt be needed anymore
not, spectator vehicle isnt stored anymore

2022-10-04 21:09 UTC, QuentinGruber commented
If you hit a dead body with a shotgun it trigger fairplay detection

2022-10-26 04:26 UTC, Z1Meme commented
@avcio9 the merge conflicts on this one are horrendous, just copy-paste dev zonepackethandlers and re-add your work i guess, idk what all you changed so I can't really fix the conflicts myself, ignore my last commit because it didn't do anything

2022-10-31 04:17 UTC, Z1Meme commented
I'll fix the errors some time this week since a lot of them are caused by the zonepackethandlers change

2022-10-31 23:00 UTC, Z1Meme commented
yep it's fucked

2022-11-01 02:19 UTC, Z1Meme commented
@QuentinGruber can't login to the server due to unknown flag not setting off ClientIsReady idk why

2022-11-23 02:48 UTC, Z1Meme commented
![image](https://user-images.githubusercontent.com/47575543/203460368-89bbf95d-5e31-4f22-91ec-4b2f6e5ecb91.png)
sideways gate / expansion bug still works (need to validate placement rotatio, should just ignore the rotation the client gives for some static rotation objects and just use a set value)

2022-11-27 21:31 UTC, Z1Meme commented
@QuentinGruber This can be merged now, it's tested with no major issues, the above issues can be fixed later.

2022-11-29 23:52 UTC, QuentinGruber approved these changes

2022-11-29 23:52 UTC, merged