Feature/config rcon managers
QuentinGruber/h1z1-server pull request #1515
Opened 2023-03-18 08:14 UTC by Z1Meme

2023-03-19 06:11 UTC, Z1Meme commented
@QuentinGruber Idk how to fix the "Test Binaries" test, I added js-yaml and that seems to be the cause

2023-03-21 21:40 UTC, QuentinGruber commented
> @QuentinGruber Idk how to fix the "Test Binaries" test, I added js-yaml and that seems to be the cause

Sorry didn't saw that, will be back tomorow and fix this if it think of it. It's just a "false" require to add so when the exe is build it include the file

2023-03-25 06:25 UTC, Z1Meme commented
@QuentinGruber this is ready to merge when the test binaries test is fixed

2023-03-25 11:23 UTC, QuentinGruber requested changes

2023-03-25 11:23 UTC, QuentinGruber commented on h1z1-server
?

2023-03-25 11:23 UTC, QuentinGruber commented on package.json
> +    "@types/js-yaml": "^4.0.5",
```suggestion
    "@types/js-yaml": "4.0.5",
```
Use fixed version ( so it need to redo the package-lock )

2023-03-25 11:23 UTC, QuentinGruber commented
i'm looking at the binaries test

2023-03-25 12:46 UTC, QuentinGruber approved these changes

2023-03-25 23:52 UTC, merged