simpleNpcs
QuentinGruber/h1z1-server pull request #1518
Opened 2023-03-21 16:44 UTC by avcio9

2023-03-25 06:28 UTC, Z1Meme commented
The position / rotation offsets must be fixed before we can merge this, otherwise people will constantly have their placements bugged, and cheaters will just place anywhere

2023-03-25 06:28 UTC, Z1Meme commented
Also this would re-enable unraidable base designs that used sideways wall placements on deck foundations / tampers

2023-03-25 06:29 UTC, Z1Meme requested changes
Need to fix offsets

2023-03-29 04:53 UTC, Z1Meme submitted a review, later dismissed

2023-03-29 21:16 UTC, QuentinGruber approved these changes

2023-03-29 21:16 UTC, merged