population numbers workaround
QuentinGruber/h1z1-server pull request #1546
Opened 2023-04-02 07:53 UTC by Z1Meme

2023-04-02 07:53 UTC, Z1Meme commented
@QuentinGruber This goes with a launcher update, do not merge without launchers updated first.

2023-04-02 11:16 UTC, QuentinGruber requested changes

2023-04-02 11:16 UTC, QuentinGruber commented on src/packets/LoginUdp/LoginUdp_11/loginpackets.ts
> +  { name: "populationNumber", type: "uint16", defaultValue: 0 },
Should put a comment about this explaining that we do modify this packet and that it's not is correct structure

2023-04-02 11:16 UTC, QuentinGruber commented on src/servers/LoginServer/loginserver.ts
> -                            populationLevel: getPopulationLevel(
if we remove it then remove the util func

2023-04-02 12:35 UTC, 0-x-2-2 commented
It could be possible to detect if this is an old client or not by changing the protocol version for custom protocol features supported or maybe just using a custom packet entirely.

2023-06-06 21:14 UTC, QuentinGruber approved these changes

2023-06-06 21:16 UTC, merged