Worn Letters, Hospital Quests & some minor changes
QuentinGruber/h1z1-server pull request #1712
Opened 2023-11-27 20:17 UTC by jasonmoonen

This MR contains the following changes:
* You can now drink water from the water towers
* Fixed world campfires and barbeques
* Punji's in PV church will actually give damage
* Added worn letter rewards
* Added hospital quest line (the toolbox key will be given until the nurse zombie can be spawned)

2023-11-30 20:58 UTC, Z1Meme requested changes

2023-11-30 20:58 UTC, Z1Meme commented on src/servers/ZoneServer2016/entities/treasurechest.ts
> +    switch (this.uniqueId) {
What is the point of uniqueId? Why not just use the ItemDefinitionId?

2023-11-30 20:58 UTC, Z1Meme commented on src/servers/ZoneServer2016/managers/worldobjectmanager.ts
> +          case "Common_Props_Campfire.adr":
Move to lootableProps, also missing world furnaces and storage containers.

2023-11-30 20:58 UTC, Z1Meme commented on src/servers/ZoneServer2016/managers/worldobjectmanager.ts
> +          case "Common_Props_Barbeque01.adr":
move to lootableProps

2023-12-01 17:14 UTC, jasonmoonen commented on src/servers/ZoneServer2016/data/Recipes.ts
> +    filterId: FilterIds.COOKING,
As it should, you never could craft this in the original game. It can only be smelted in campfires / barbecues

2023-12-01 22:06 UTC, jasonmoonen commented on src/servers/ZoneServer2016/data/Recipes.ts
> +    filterId: FilterIds.COOKING,
Ah alright! I forgot this was possible. I’ll take a loot at this later.

2023-12-10 15:07 UTC, QuentinGruber requested changes

2023-12-11 13:12 UTC, merged