kronicways-ServerItemDefinitions-changes
QuentinGruber/h1z1-server pull request #1856
Opened 2024-01-25 14:13 UTC by QuentinGruber

2024-01-25 14:13 UTC, QuentinGruber commented
based on https://github.com/QuentinGruber/h1z1-server/pull/1849

2024-01-25 14:13 UTC, QuentinGruber commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/QuentinGruber/h1z1-server/1856?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `dev`
  * **PR #1850** <a href="https://app.graphite.dev/github/pr/QuentinGruber/h1z1-server/1850?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1851** <a href="https://app.graphite.dev/github/pr/QuentinGruber/h1z1-server/1851?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #1852** <a href="https://app.graphite.dev/github/pr/QuentinGruber/h1z1-server/1852?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #1853** <a href="https://app.graphite.dev/github/pr/QuentinGruber/h1z1-server/1853?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #1854** <a href="https://app.graphite.dev/github/pr/QuentinGruber/h1z1-server/1854?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #1855** <a href="https://app.graphite.dev/github/pr/QuentinGruber/h1z1-server/1855?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
              * **PR #1856** <a href="https://app.graphite.dev/github/pr/QuentinGruber/h1z1-server/1856?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/QuentinGruber/h1z1-server/1856?utm_source=stack-comment).

2024-01-25 16:34 UTC, Nikolassparrow commented
Players should also spawn with a Jagged skinning knife so they can harvest animals 👍

2024-01-25 16:38 UTC, QuentinGruber commented
> Players should also spawn with a Jagged skinning knife so they can harvest animals 👍

true add this to your harvest PR :cowboy_hat_face:

2024-01-29 04:04 UTC, Z1Meme requested changes

2024-01-29 04:04 UTC, Z1Meme commented on data/2016/dataSources/ServerItemDefinitions.json
> +        "ID": 1899,
what is the point of this?

2024-01-29 04:04 UTC, Z1Meme commented on data/2016/dataSources/ServerItemDefinitions.json
> +        "ID": 1899,
This makes no sense?

2024-01-31 14:43 UTC, closed without merging