bugfix/allWeaponsRandomDura
QuentinGruber/h1z1-server pull request #1906
Opened 2024-02-04 21:46 UTC by Nikolassparrow

Was a slight oversight in #1899. Only crowbars (for now) should have random durability for weapons

2024-02-05 15:53 UTC, QuentinGruber approved these changes
Up to you but i found that actually cool

2024-02-05 16:15 UTC, Nikolassparrow commented
> Was it that bad ? actually found it cool that you could found almost broke Ar and stuff

I agree, weapons used to spawn with random durability back in the day, but I mainly made this PR to prevent things like flashlights from having durability 😂 

I'll update this PR to allow guns, hammers, and crowbars to the random durability list :D

2024-02-06 20:28 UTC, Nikolassparrow commented
Added a check for an item being crafted so crafted items don't get applied random durability, only item pickups.

2024-02-08 14:50 UTC, QuentinGruber requested changes
Pr has render issue ( backpack  ) and circular issue in the vehicle object ( time ) which lead to a crash

2024-02-08 14:53 UTC, QuentinGruber commented
maybe not linked to this pr need to update it based on dev

2024-02-08 16:48 UTC, QuentinGruber requested changes
Ok seems fist still have the issue

2024-02-08 20:07 UTC, Nikolassparrow commented
> Ok seems fist still have the issue

Wasn't able to re-produce the issue, how did you do it?

2024-02-08 23:12 UTC, QuentinGruber commented
> > Ok seems fist still have the issue
> 
> Wasn't able to re-produce the issue, how did you do it?

it was an old character my bad

2024-02-08 23:14 UTC, QuentinGruber commented on src/servers/ZoneServer2016/zoneserver.ts
> +    lastGeneratedTime: number = 0
maybe just changing lastGeneratedTime to a boolean would make the trick ?

2024-02-08 23:14 UTC, QuentinGruber approved these changes

2024-02-08 23:15 UTC, merged