Some more fixes
QuentinGruber/h1z1-server pull request #2189
Opened 2024-10-23 18:55 UTC by jasonmoonen

1. Fixes group kick from UI
2. Send base parts before players are sent to the clients
3. Increase range for base parts so players are hidden behind them
4. You can now specify a player name in the parachute command

2024-10-23 19:58 UTC, avcio9 commented
Do we want to see the whispers?

2024-10-24 13:47 UTC, QuentinGruber requested changes

2024-10-24 13:47 UTC, QuentinGruber commented on src/servers/ZoneServer2016/handlers/commands/commands.ts
> +          `[${client.character.name} whispered to ${targetClient.character.name}]: ${message}`
.

2024-10-24 13:59 UTC, QuentinGruber approved these changes

2024-10-24 13:59 UTC, merged