2016item definitions
QuentinGruber/h1z1-server pull request #455
Opened 2021-09-14 07:09 UTC by Z1Meme

2021-09-14 17:06 UTC, QuentinGruber commented on .vscode/tasks.json
> +	"version": "2.0.0",
wut wasn't this already there

2021-09-20 07:11 UTC, QuentinGruber requested changes

2021-09-20 07:11 UTC, QuentinGruber commented on package.json
> +    "fs": "^0.0.1-security",
this should be removed. "fs" is already in nodejs

2021-09-21 20:41 UTC, Z1Meme reviewed
👍

2021-09-21 20:42 UTC, Z1Meme reviewed
👍

2021-09-21 20:55 UTC, QuentinGruber approved these changes

2021-09-21 20:57 UTC, merged