2016loadouts
QuentinGruber/h1z1-server pull request #477
Opened 2021-09-21 20:43 UTC by Z1Meme

2021-09-27 18:25 UTC, QuentinGruber requested changes

2021-09-27 18:25 UTC, QuentinGruber commented on src/packets/ClientProtocol/ClientProtocol_860/h1z1packets.ts
> +    obj["unknown7_float"] = v.value / 100; // not 100% sure about name
Idk why it keep being renamed, be sure to not merge that

2021-09-27 18:25 UTC, QuentinGruber commented on src/servers/ZoneServer2016/classes/character.ts
> +  loadout: any[];
Creating an interface called "Loadout" can be usefull instead of using any[]

2021-09-27 18:25 UTC, QuentinGruber commented on src/servers/ZoneServer2016/classes/character.ts
> +    this.loadout = []
if it's always empty at start, defined it like this `loadout: any[] = [];` before the constructor

2021-09-27 18:25 UTC, QuentinGruber commented on package.json
> +    "zlib": "^1.0.5"
uninstall this , https://www.npmjs.com/package/zlib it's a package from over a decade now nodejs have zlib built inside the runtime ( you can use it by `require("zlib")` ) https://nodejs.org/dist/latest-v16.x/docs/api/zlib.html#zlib_threadpool_usage_and_performance_considerations

2021-09-27 18:25 UTC, QuentinGruber commented on src/servers/ZoneServer2016/zoneserver.ts
> +      if (fixed) return Number(num.toFixed(0));
```suggestion
      return Number(fixed?num.toFixed(0):num);
```

2021-10-02 04:30 UTC, Z1Meme commented
Ready for update

2021-10-02 14:11 UTC, QuentinGruber approved these changes

2021-10-02 14:12 UTC, QuentinGruber requested changes
hm wait

2021-10-02 14:33 UTC, merged