Remove inventory on death/ fix some explosive stuff
QuentinGruber/h1z1-server pull request #707
Opened 2022-03-09 11:03 UTC by avcio9

2022-03-09 18:18 UTC, QuentinGruber requested changes

2022-03-09 18:50 UTC, avcio9 commented on src/servers/ZoneServer2016/classes/character.ts
> +        if (client.character.resources.food != food) {
i define them before the loop so the packet is sent only if they change

2022-03-10 17:12 UTC, avcio9 commented on src/servers/ZoneServer2016/zoneserver.ts
> +    this._temporatyObjects = {};
Yeah, but doesnt matter :D

2022-03-16 23:57 UTC, QuentinGruber approved these changes

2022-03-16 23:57 UTC, merged