(hopefully) fixed duplicate name exploit when creating a character
QuentinGruber/h1z1-server pull request #976
Opened 2022-07-14 04:02 UTC by Z1Meme

2022-07-14 04:02 UTC, Z1Meme commented
@QuentinGruber I was playing my server and someone hopped on it with my same name, didn't know we didn't check this lol

2022-07-14 09:37 UTC, QuentinGruber requested changes

2022-07-14 09:37 UTC, QuentinGruber commented on src/servers/LoginServer/loginserver.ts
> +        if(this._soloMode) {
```suggestion
        if(!this._soloMode) {
```

2022-07-14 09:37 UTC, QuentinGruber commented on src/servers/LoginServer/loginserver.ts
> +          .findOne({ characterName: packet.result.characterName });
```suggestion
          .findOne({ characterName: packet.result.characterName, serverId: baseResponse.serverId });
```

2022-07-14 09:39 UTC, QuentinGruber commented
> @QuentinGruber I was playing my server and someone hopped on it with my same name, didn't know we didn't check this lol

There was an old implementation on live-login-server, i will removed it and add also the blackListEntries verification on this PR, you can check it there https://github.com/H1emu/live-login-server

2022-07-15 16:53 UTC, QuentinGruber commented on src/servers/LoginServer/loginserver.ts
> +          .findOne({ characterName: packet.result.characterName });
This still need to be done @Z1Meme

2022-07-18 17:05 UTC, QuentinGruber approved these changes

2022-07-18 17:05 UTC, merged